on:
  release:
    types: [created]
name: Release binaries
jobs:
  generate:
    name: Create release-artifacts
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build binaries
        uses: skx/github-action-build@master
        with:
          builder: build.sh
      - name: Upload the binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/golivereload*'
