name: Release binaries 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#   release:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: go get github.com/tools/godep
    - run: ~/go/bin/godep restore
    - run: ./build.sh
#     - name: Upload the binaries
#       uses: skx/github-action-publish-binaries@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         args: 'build/golivereload*'
